import {
  course1,
  course2,
  course3,
  course4,
  course5,
  course6,
} from "@/assets";
import { Course } from "./CourseCard";

export const CATEGORIES = [
  "Featured",
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Digital Illustration",
  "Film & Video",
  "Crafts",
  "Freelance & Entrepreneurship",
  "Graphic Design",
  "Photography",
  "Productivity",
  "Web Development",
  "Data Science",
  "Cooking",
  "+ More",
];

export const COURSES: Course[] = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course1,
    price: "$25",
    period: "/lifetime",
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course2,
    price: "$25",
    period: "/lifetime",
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course3,
    price: "$25",
    period: "/lifetime",
  },
  {
    id: 4,
    title: "Balancing Productivity an...",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course4,
    price: "$25",
    period: "/lifetime",
  },
  {
    id: 5,
    title: "Mastering Money Manage...",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course5,
    price: "$25",
    period: "/lifetime",
  },
  {
    id: 6,
    title: "From Idea to Startup Succ...",
    author: "purepearl studio",
    rating: "4.5",
    level: "Beginner",
    image: course6,
    price: "$25",
    period: "/lifetime",
  },
];
